name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: dotnet test
      
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: ssh-keyscan 209.97.129.212 >> ~/.ssh/known_hosts

      - run: ssh -tt david2@209.97.129.212 'rm -rf /var/www/manx-corpus/OpenData/{*,.*}'
        continue-on-error: true
        timeout-minutes: 1
      
      - name: Copy Data to server
        run: scp -r "$GITHUB_WORKSPACE/OpenData" david2@209.97.129.212:/var/www/manx-corpus/
        timeout-minutes: 1
        
      - name: Rebuild
        run: ssh -t david2@209.97.129.212 'sudo /bin/systemctl stop manx-corpus.service && cd /var/www/manx-corpus/ && dotnet publish'
            
        # even if the above fails, we want a working site
      - name: Restart Service
        run: ssh -t david2@209.97.129.212 'sudo /bin/systemctl start manx-corpus.service'